# Generated by Django 5.2.1 on 2025-05-19 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0007_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(verbose_name='Địa chỉ nhận hàng')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Số điện thoại liên hệ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email liên hệ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Nội dung ghi chú')),
                ('total_amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fashion.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.product')),
            ],
        ),
    ]
