# Generated by Django 5.2.1 on 2025-05-19 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0008_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_key',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ nhận hàng'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email liên hệ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại liên hệ'),
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Địa chỉ nhận hàng')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Số điện thoại liên hệ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email liên hệ')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
