# Generated by Django 5.2.1 on 2025-05-21 09:28

import fashion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0009_order_order_key_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/default.jpg', null=True, upload_to=fashion.models.user_directory_path),
        ),
    ]
