# Generated by Django 5.2.1 on 2025-05-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0010_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isVerified_email',
            field=models.BooleanField(default=False, verbose_name='Email đã xác thực'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isVerified_phone',
            field=models.BooleanField(default=False, verbose_name='Số điện thoại đã xác thực'),
        ),
    ]
