# Generated by Django 5.2.1 on 2025-05-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0011_userprofile_isverified_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='contact_phone',
            new_name='phone',
        ),
    ]
