# Generated by Django 5.2.1 on 2025-05-23 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0012_rename_contact_email_usercontact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='phone',
            new_name='contact_phone',
        ),
    ]
