# Generated by Django 5.2.1 on 2025-05-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0013_rename_email_usercontact_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Trạng thái đơn hàng'),
        ),
    ]
