# Generated by Django 5.2.1 on 2025-05-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0014_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
